const OtherProjects = [
  {
    url: "https://pavellaptev.github.io/squircle-houdini-css/",
    title: "Squircle Houdini CSS module",
    text: "A lightweight CSS module for cubic-bezier squircles.",
    date: "15.4.2021",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/kinetik-typography-three-js/#/",
    title: "Kinetic Typography with ThreeJS",
    text: "How to create motion and visual illusions with simple 3d shapes and tile text textures.",
    date: "15.1.2021",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/context-cursor/",
    title: "Context Cursor",
    text: "A cursor that takes the shape of the hovered element. Inspired by iPad pointer.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/warp-svg/",
    title: "Warp SVG Online!",
    text: "A simple online tool that allows you to warp, bend, and distort SVG files.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/web-dark-ages/",
    title: "Dark Ages of the Web",
    text: "The year 1994 when all began and the great era when the web we know today was born…",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/tiny-flexbox-grid-system/",
    title: "Flexbox SCSS grid Framework",
    text: "Experience in making complex but simple CSS frameworks based on Flexbox and SCSS.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/brutalist-buildings/",
    title: "BRUTALISM KARTE",
    text: "As a fan of Brutalist architecture, I made an interactive map using D3.js. You can manage buildings on the map by date of construction with a range slider.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://medium.com/@PavelLaptev/design-tokens-with-figma-aef25c42430f",
    title: "Design tokens with Figma",
    text: "A new article about Figma API. In this article I will show you how to generate design tokens via Figma API and convert them through the Style Dictionary.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/wunderzin/promo/",
    title: "Wûnderzin free Ui Kit",
    text: "Figma free UI Kit of a nonexistent online magazine Wûnderzine. A few pages and many components.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/markdown-theme-shell/public/",
    title: "Markdown Theme Shell",
    text: "Often, while working on a design system, we have to keep detailed documentation. For this purpose, the “Markdown Theme Shell” was made, it parses the markdown file in the HTML page, creating a sidebar and content area.",
    date: "0.0.0",
    new: false,
  },
  {
    url: "https://pavellaptev.github.io/JSON-from-Figma",
    title: "JSON from figma file",
    text: "To demonstrate the power of Figma API I made this webpage as an experiment. On this page you could get a full JSON structure, pages and nested artboards, and also filter all by a flag name.",
    date: "0.0.0",
    new: false,
  },
];

export default OtherProjects;
