import Head from "next/head";
import type { NextPage } from "next";

import styles from "./app.module.scss";

import {
  Hero,
  Plugins,
  Resources,
  Pets,
  Articles,
  Experience
} from "../sections";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pavel Laptev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Plugins />
        <Resources />
        <Pets />
        <Articles />
        <Experience />
      </main>
    </>
  );
};

export default Home;
