import Head from "next/head";
import type { NextPage } from "next";
import Script from "next/script";

import styles from "./app.module.scss";

import {
  Hero,
  Plugins,
  Resources,
  Pets,
  Articles,
  Experience
} from "../sections";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pavel Laptev</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/ico-32.png" />
        <link rel="icon" href="/ico-64.png" />
        <link rel="icon" href="/ico-192.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Pavel Laptev — digital designer" />

        <script async src="https://cdn.splitbee.io/sb.js"></script>
      </Head>

      <main className={styles.main}>
        <Hero />
        <Plugins />
        <Resources />
        <Pets />
        <Articles />
        <Experience />
      </main>

      {/* hotjar */}
      <Script
        id="hotjar"
        dangerouslySetInnerHTML={{
          __html: `
          (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:3229966,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
          `
        }}
      />
    </>
  );
};

export default Home;
